version: 0.2   
 
phases:   
  install: 
    runtime-versions: 
      java: openjdk11 
  pre_build:   
    commands:   
      - echo Logging in to Amazon ECR...   
      - aws --version   
      - pwd   
      - $(aws ecr get-login --no-include-email --region us-east-2)   
      - REPOSITORY_URI=<ECR URL of Project>
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)         
      - echo Branch..................... $BRANCH
      - IMAGE_TAG=${BRANCH}-$COMMIT_HASH
      - echo REPOSITORY_URI=$REPOSITORY_URI
      - echo COMMIT_HASH=$COMMIT_HASH
      - echo IMAGE_TAG=$IMAGE_TAG
  build:   
    commands:   
    - echo started the build on `date`
    - mvn clean package
    - echo Building the Docker image...
    - docker build -f docker/Dockerfile -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:   
    commands:   
      - echo Build completed on `date`   
      - echo Pushing the Docker images...   
      - docker push $REPOSITORY_URI:$IMAGE_TAG 
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
   
artifacts:   
  files:   
     - imageDetail.json
     - appspec.yaml
     - taskdef.json
     - appspec_prod.yaml
     - taskdef_prod.json
     - appspec_pilot.yaml
     - taskdef_pilot.json 
  discard-paths: yes

cache:
  paths:
  - '/root/.m2/**/*'